services:
  - type: web
    name: rank-check
    env: node
    buildCommand: npm install
    startCommand: node index.js
    aptPackages:
      - build-essential
      - libcairo2-dev
      - libpango1.0-dev
      - libjpeg-dev
      - libgif-dev
      - librsvg2-dev